using ChroniclerWeb.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ChroniclerWeb.Services.NewFolder
{
    public class PdfExportService : IPdfExportService
    {
        public byte[] ExportCharacterSheet(Character character)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(1.5f, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header()
                        .Text($"{character.Name}")
                        .SemiBold().FontSize(24).FontColor(Colors.Blue.Darken2);

                    page.Content()
                        .PaddingVertical(1f, Unit.Centimetre)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            // Character Info
                            column.Item().Row(row =>
                            {
                                row.RelativeItem().Column(col =>
                                {
                                    col.Item().Text($"Race: {character.Race}");
                                    col.Item().Text($"Class: {character.Class}");
                                    col.Item().Text($"Type: {character.Type}");
                                });
                                row.RelativeItem().Column(col =>
                                {
                                    col.Item().Text($"Status: {character.Status}");
                                    col.Item().Text($"Role: {character.Role ?? "N/A"}");
                                    col.Item().Text($"NPC Role: {character.NPCRole}");
                                });
                            });

                            // Stats section
                            column.Item().PaddingTop(10).Text("Ability Scores").Bold().FontSize(16).FontColor(Colors.Grey.Darken1);

                            column.Item().Table(table =>
                            {
                                table.ColumnsDefinition(columns =>
                                {
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                    columns.RelativeColumn();
                                });

                                table.Header(header =>
                                {
                                    header.Cell().Text("STR").Bold();
                                    header.Cell().Text("DEX").Bold();
                                    header.Cell().Text("CON").Bold();
                                    header.Cell().Text("INT").Bold();
                                    header.Cell().Text("WIS").Bold();
                                    header.Cell().Text("CHA").Bold();
                                });

                                table.Cell().AlignCenter().Text(character.Strength.ToString());
                                table.Cell().AlignCenter().Text(character.Dexterity.ToString());
                                table.Cell().AlignCenter().Text(character.Constitution.ToString());
                                table.Cell().AlignCenter().Text(character.Intelligence.ToString());
                                table.Cell().AlignCenter().Text(character.Wisdom.ToString());
                                table.Cell().AlignCenter().Text(character.Charisma.ToString());
                            });

                            // Description
                            if (!string.IsNullOrEmpty(character.Description))
                            {
                                column.Item().PaddingTop(10).Text("Description").Bold().FontSize(16).FontColor(Colors.Grey.Darken1);
                                column.Item().Text(character.Description);
                            }

                            // Notes
                            if (!string.IsNullOrEmpty(character.SharedNotes))
                            {
                                column.Item().PaddingTop(10).Text("Notes").Bold().FontSize(16).FontColor(Colors.Grey.Darken1);
                                column.Item().Text(character.SharedNotes);
                            }

                            // Footer
                            column.Item().PaddingTop(30).AlignCenter().Text("Generated by The Chronicler").FontSize(8).FontColor(Colors.Grey.Medium);
                        });
                });
            });

            return document.GeneratePdf();
        }

        public byte[] ExportCampaignSummary(Campaign campaign, List<Session> sessions)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(1.5f, Unit.Centimetre);
                    page.PageColor(Colors.White);

                    page.Header()
                        .Text($"Campaign: {campaign.Name}")
                        .SemiBold().FontSize(24).FontColor(Colors.Grey.Darken3);

                    page.Content()
                        .PaddingVertical(1f, Unit.Centimetre)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            // Campaign Info
                            column.Item().Row(row =>
                            {
                                row.RelativeItem().Column(col =>
                                {
                                    col.Item().Text($"Game System: {campaign.GameSystem ?? "N/A"}");
                                    col.Item().Text($"Status: {campaign.Status}");
                                });
                            });

                            // Description
                            if (!string.IsNullOrEmpty(campaign.Description))
                            {
                                column.Item().PaddingTop(10).Text("Description").Bold().FontSize(14);
                                column.Item().Text(campaign.Description);
                            }

                            // Sessions
                            column.Item().PaddingTop(15).Text($"Sessions ({sessions.Count})").Bold().FontSize(14);

                            foreach (var session in sessions.Take(10))
                            {
                                column.Item().PaddingTop(5).Row(row =>
                                {
                                    row.ConstantItem(60).Text($"#{session.SessionNumber}").Bold();
                                    row.RelativeItem().Text(session.Title);
                                    row.ConstantItem(100).AlignRight().Text(session.SessionDate.ToString("MMM dd, yyyy")).FontSize(9);
                                });
                                if (!string.IsNullOrEmpty(session.Summary))
                                {
                                    column.Item().PaddingLeft(60).Text(session.Summary).FontSize(9).FontColor(Colors.Grey.Medium);
                                }
                            }

                            column.Item().PaddingTop(30).AlignCenter().Text("Generated by The Chronicler").FontSize(8).FontColor(Colors.Grey.Medium);
                        });
                });
            });

            return document.GeneratePdf();
        }
    }
}
